### ISSUE TITLE
[Feature request] Handle spaces in deck names

### ISSUE THREAD

**Issue by glutanimate** [adelq/anki_hierarchy#1]
Hi there,

first of all: Great job on the add-on! I was checking back with that thread on Reddit and was happy to see that someone ended up taking on this idea.

One enhancement I feel the add-on might benefit from is a way to handle whitespace in deck names. Perhaps replacing all spaces with underscores might work?

**Comment by adelq** [comment]
Thanks! Ah good idea, I completely forgot about spaces/special characters in deck names that aren't valid tag names, should be an easy fix.

**Comment by adelq** [comment]
Fixed by pull request #2. Thanks!

**Comment by glutanimate** [comment]
Working perfectly here. Thanks!
