### ISSUE TITLE
Tags created, but not applied to cards

### ISSUE THREAD

**Issue by Albriech** [adelq/anki_hierarchy#5]
One of my decks already had a hierarchical tags organization in addition to subdecks. When I ran the addon on the deck containing the subdeck in question, the cards were moved to the deck and the tags appeared in the browser, but the tags were empty. The addon worked perfectly for the other two subdecks.
These decks are all in the thousands of cards.
Maybe it's an Anki thing and each card can only have one hierarchical tag?

**Comment by adelq** [comment]
Interesting, I've never tried it on a deck with both hierarchical tags and subdecks. Do you have a link to a deck so I can look into it further?

Thanks for the report!

**Comment by Albriech** [comment]
The deck is from r/medicalschoolanki. The hierarchical tags it came with serve the same purpose as your addon so I'm good. Apart from this, it worked like a charm, so thank you! [Direct link](https://mega.nz/#!Cf4QnSLR!fefExs-QYhdxqi2FFAz3EVd56reQ7gh7Iyp1WIuyE08), [Reddit link](https://www.reddit.com/r/medicalschoolanki/comments/91om17/lolnotacop_bugsdrugs_reorg_and_hierarchical_tag/e30kfqx/?st=jld0yk3d&sh=2eeaa9bd)

**Comment by adelq** [comment]
I figured out the issue, the apostrophe in the deck title was causing issues, so I've decided the appropriate fix is to remove all apostrophes from now on (63dd1686ccb49f4f3a001f18214df7556d065c5c). Thanks for reporting the issue, the updated version should be up soon!
