### ISSUE TITLE
Combining sub decks deletes cards

### ISSUE THREAD

**Issue by trailerz** [adelq/anki_hierarchy#8]
I have acquired a deck with many subdecks. When I converted all these subdecks to tags and **kept** the subdecks all the cards were still there (the process worked!). When I tried to **combine** the subdecks into a parent deck it deleted all of the cards. I tried the "combining" way after converting to tags while keeping the subdecks and after rebooting a backup of the same cards before converting to tags. The parent deck has around 16,000 cards for reference.

**Comment by adelq** [comment]
Could you post the deck you're having trouble with?
Does this issue happen with any other decks?

**Comment by adelq** [comment]
Fixed by #10, please update the extension and try again
